# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: runtime_api/frame_transport.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'runtime_api/frame_transport.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!runtime_api/frame_transport.proto\x12\x07runtime\"{\n\nFrameChunk\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63hunk_index\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x14\n\x0c\x63ontent_type\x18\x04 \x01(\t\x12\x12\n\ntotal_size\x18\x05 \x01(\x04\x12\x0e\n\x06sha256\x18\x06 \x01(\t\"\x93\x01\n\x0e\x46rameReference\x12\x11\n\ttransport\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\x12\x10\n\x08\x66rame_id\x18\x03 \x01(\t\x12\x12\n\nsize_bytes\x18\x04 \x01(\x04\x12\x0e\n\x06sha256\x18\x05 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x06 \x01(\t\x12\x12\n\nchunk_size\x18\x07 \x01(\r\"&\n\x13\x44\x65leteFrameResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\x32\xd6\x01\n\x0e\x46rameTransport\x12=\n\x0bUploadFrame\x12\x13.runtime.FrameChunk\x1a\x17.runtime.FrameReference(\x01\x12?\n\rDownloadFrame\x12\x17.runtime.FrameReference\x1a\x13.runtime.FrameChunk0\x01\x12\x44\n\x0b\x44\x65leteFrame\x12\x17.runtime.FrameReference\x1a\x1c.runtime.DeleteFrameResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'runtime_api.frame_transport_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMECHUNK']._serialized_start=46
  _globals['_FRAMECHUNK']._serialized_end=169
  _globals['_FRAMEREFERENCE']._serialized_start=172
  _globals['_FRAMEREFERENCE']._serialized_end=319
  _globals['_DELETEFRAMERESPONSE']._serialized_start=321
  _globals['_DELETEFRAMERESPONSE']._serialized_end=359
  _globals['_FRAMETRANSPORT']._serialized_start=362
  _globals['_FRAMETRANSPORT']._serialized_end=576
# @@protoc_insertion_point(module_scope)
