services:
  cooperativefeaturefusiondetectionviz-agent:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PIP_INDEX_URL: ${PIP_INDEX_URL:-https://pypi.tuna.tsinghua.edu.cn/simple}
        PIP_EXTRA_INDEX_URL: ${PIP_EXTRA_INDEX_URL:-https://download.pytorch.org/whl/cu128}
    image: cooperativefeaturefusiondetectionviz-agent:0.1.5
    container_name: cooperativefeaturefusiondetectionviz-agent
    ports:
      - "9032:9032"
    environment:
      A2A_AGENT_URL: http://localhost:9032
      MODEL_CHECKPOINT_PATH: /app/checkpoints/point_pillar_where2comm/
      QT_GRAPHICSSYSTEM: native
      # NATS_SERVER_URL: nats://nats:4222
      NATS_SERVER_URL: nats://host.docker.internal:4222
      NATS_SUBJECT: workflow.demo.perception2feature.result
      NATS_DURABLE: workflow-demo-perception2feature-result
    extra_hosts:
      - "host.docker.internal:host-gateway"
    gpus: all
