apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-b
  template:
    metadata:
      labels:
        app: agent-b
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values: ["agent-grpc"]
                topologyKey: kubernetes.io/hostname
      containers:
        - name: agent-b
          image: agent-b-worker:v5
          imagePullPolicy: IfNotPresent
          env:
            - name: NATS_SERVERS
              value: "nats://nats:4222"
            - name: NATS_JETSTREAM_DOMAIN
              value: "hub"
            - name: NATS_STREAM_SUBJECTS
              value: "workflow.>"
            - name: CLUSTER_ID
              value: "__EDGE_CLUSTER_ID__"
            - name: IN_SUBJECT
              value: "workflow.__EDGE_CLUSTER_ID__.agent.b.in"
            - name: C_IN_SUBJECT
              value: "workflow.__EDGE_CLUSTER_ID__.agent.c.in"
            - name: OUT_SUBJECT
              value: "workflow.__EDGE_CLUSTER_ID__.agent.grpc.reply.default"
            - name: B_REPLY_PREFIX
              value: "workflow.__EDGE_CLUSTER_ID__.agent.b.c.reply"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
