apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-grpc
  template:
    metadata:
      labels:
        app: agent-grpc
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values: ["agent-b"]
                topologyKey: kubernetes.io/hostname
      containers:
        - name: agent-grpc
          image: agent-grpc:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: NATS_SERVERS
              value: "nats://nats:4222"
            - name: NATS_JETSTREAM_DOMAIN
              value: "hub"
            - name: NATS_STREAM_SUBJECTS
              value: "workflow.>"
            - name: CLUSTER_ID
              value: "__EDGE_CLUSTER_ID__"
            - name: REQ_SUBJECT
              value: "workflow.__EDGE_CLUSTER_ID__.agent.b.in"
            - name: REPLY_SUBJECT_PREFIX
              value: "workflow.__EDGE_CLUSTER_ID__.agent.grpc.reply"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          ports:
            - containerPort: 50051
