apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-a
  template:
    metadata:
      labels:
        app: agent-a
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values: ["agent-b"]
                topologyKey: kubernetes.io/hostname
      containers:
        - name: agent-a
          image: agent-a-grpc:v2
          imagePullPolicy: IfNotPresent
          env:
            - name: NATS_SERVERS
              value: "nats://nats:4222"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          ports:
            - containerPort: 50051
