apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-a-config
  labels:
    app: nats-a
data:
  nats.conf: |
    server_name: "nats-a"
    port: 4222
    http_port: 8222
    max_payload: 8388608
    jetstream {
      store_dir: "/data"
    }
    cluster {
      name: "gw-a"
      listen: "0.0.0.0:6222"
      routes: [
        "nats-route://127.0.0.1:6222"
      ]
    }
    gateway {
      name: "gw-a"
      listen: "0.0.0.0:7222"
      advertise: "10.112.136.44:7222"
      gateways: [
        { name: "gw-b", urls: ["nats://10.112.221.121:7222"] }
      ]
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-a
  labels:
    app: nats-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-a
  template:
    metadata:
      labels:
        app: nats-a
    spec:
      containers:
        - name: nats
          image: docker.m.daocloud.io/library/nats:2.10
          args:
            - "-c"
            - "/etc/nats-config/nats.conf"
          ports:
            - containerPort: 4222
              name: client
            - containerPort: 6222
              name: cluster
            - containerPort: 7222
              name: gateway
            - containerPort: 8222
              name: monitor
          volumeMounts:
            - name: nats-config
              mountPath: /etc/nats-config
      volumes:
        - name: nats-config
          configMap:
            name: nats-a-config
---
apiVersion: v1
kind: Service
metadata:
  name: nats-a
  labels:
    app: nats-a
spec:
  selector:
    app: nats-a
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: cluster
      port: 6222
      targetPort: 6222
    - name: gateway
      port: 7222
      targetPort: 7222
    - name: monitor
      port: 8222
      targetPort: 8222
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  labels:
    app: nats-a
    alias-for: nats-a
spec:
  selector:
    app: nats-a
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: monitor
      port: 8222
      targetPort: 8222
  type: ClusterIP
