apiVersion: apps/v1
kind: Deployment
metadata:
  name: perception2intermediatefeature-agent
  labels:
    app: perception2intermediatefeature-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perception2intermediatefeature-agent
  template:
    metadata:
      labels:
        app: perception2intermediatefeature-agent
    spec:
      containers:
        - name: perception2intermediatefeature-agent
          image: perception2intermediatefeature-agent:0.1.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9031
              name: http
          env:
            - name: A2A_AGENT_URL
              value: http://192.168.49.2:30391
            - name: MCP_SERVER_HOST
              value: 10.112.136.44
            - name: MCP_SERVER_PORT
              value: "8123"
            - name: MODEL_CHECKPOINT_PATH
              value: /app/checkpoints/point_pillar_where2comm/
            - name: FRONTEND_CALLBACK_URL
              value: http://host.minikube.internal:9002/temp/post_data
            - name: NATS_SERVERS
              value: nats://nats:4222
            - name: NATS_SERVER_URL
              value: nats://nats:4222
            - name: NATS_JETSTREAM_DOMAIN
              value: hub
            - name: NATS_STREAM_SUBJECTS
              value: workflow.>
            - name: NATS_SUBJECT
              value: workflow.demo.perception2feature.result.dx86.0601
            - name: AGENT_MAX_CONCURRENT_TASKS
              value: "1"
            - name: AGENT_ID
              value: perception2intermediatefeature-agent
            - name: INSTANCE_ID
              value: perception2intermediatefeature-agent-instance-1
          resources:
            requests:
              nvidia.com/gpu: "1"
            limits:
              nvidia.com/gpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: perception2intermediatefeature-agent
  labels:
    app: perception2intermediatefeature-agent
spec:
  selector:
    app: perception2intermediatefeature-agent
  ports:
    - name: http
      protocol: TCP
      port: 9031
      nodePort: 30391
      targetPort: 9031
  type: NodePort
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: perception2intermediatefeature-agent
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: perception2intermediatefeature-agent
  endpoints:
    - port: http
      path: /metrics/
      interval: 15s
      scrapeTimeout: 10s
