# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from runtime_api import frame_transport_pb2 as runtime__api_dot_frame__transport__pb2


class FrameTransportStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFrame = channel.stream_unary(
                '/runtime.FrameTransport/UploadFrame',
                request_serializer=runtime__api_dot_frame__transport__pb2.FrameChunk.SerializeToString,
                response_deserializer=runtime__api_dot_frame__transport__pb2.FrameReference.FromString,
                _registered_method=True)
        self.DownloadFrame = channel.unary_stream(
                '/runtime.FrameTransport/DownloadFrame',
                request_serializer=runtime__api_dot_frame__transport__pb2.FrameReference.SerializeToString,
                response_deserializer=runtime__api_dot_frame__transport__pb2.FrameChunk.FromString,
                _registered_method=True)
        self.DeleteFrame = channel.unary_unary(
                '/runtime.FrameTransport/DeleteFrame',
                request_serializer=runtime__api_dot_frame__transport__pb2.FrameReference.SerializeToString,
                response_deserializer=runtime__api_dot_frame__transport__pb2.DeleteFrameResponse.FromString,
                _registered_method=True)


class FrameTransportServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadFrame(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrameTransportServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFrame': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFrame,
                    request_deserializer=runtime__api_dot_frame__transport__pb2.FrameChunk.FromString,
                    response_serializer=runtime__api_dot_frame__transport__pb2.FrameReference.SerializeToString,
            ),
            'DownloadFrame': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFrame,
                    request_deserializer=runtime__api_dot_frame__transport__pb2.FrameReference.FromString,
                    response_serializer=runtime__api_dot_frame__transport__pb2.FrameChunk.SerializeToString,
            ),
            'DeleteFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFrame,
                    request_deserializer=runtime__api_dot_frame__transport__pb2.FrameReference.FromString,
                    response_serializer=runtime__api_dot_frame__transport__pb2.DeleteFrameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'runtime.FrameTransport', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('runtime.FrameTransport', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FrameTransport(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadFrame(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/runtime.FrameTransport/UploadFrame',
            runtime__api_dot_frame__transport__pb2.FrameChunk.SerializeToString,
            runtime__api_dot_frame__transport__pb2.FrameReference.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/runtime.FrameTransport/DownloadFrame',
            runtime__api_dot_frame__transport__pb2.FrameReference.SerializeToString,
            runtime__api_dot_frame__transport__pb2.FrameChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.FrameTransport/DeleteFrame',
            runtime__api_dot_frame__transport__pb2.FrameReference.SerializeToString,
            runtime__api_dot_frame__transport__pb2.DeleteFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
