# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\"\x1c\n\x0cInferRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1f\n\rInferResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2B\n\x0c\x41gentService\x12\x32\n\x05Infer\x12\x13.agent.InferRequest\x1a\x14.agent.InferResponseb\x06proto3')



_INFERREQUEST = DESCRIPTOR.message_types_by_name['InferRequest']
_INFERRESPONSE = DESCRIPTOR.message_types_by_name['InferResponse']
InferRequest = _reflection.GeneratedProtocolMessageType('InferRequest', (_message.Message,), {
  'DESCRIPTOR' : _INFERREQUEST,
  '__module__' : 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.InferRequest)
  })
_sym_db.RegisterMessage(InferRequest)

InferResponse = _reflection.GeneratedProtocolMessageType('InferResponse', (_message.Message,), {
  'DESCRIPTOR' : _INFERRESPONSE,
  '__module__' : 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.InferResponse)
  })
_sym_db.RegisterMessage(InferResponse)

_AGENTSERVICE = DESCRIPTOR.services_by_name['AgentService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INFERREQUEST._serialized_start=22
  _INFERREQUEST._serialized_end=50
  _INFERRESPONSE._serialized_start=52
  _INFERRESPONSE._serialized_end=83
  _AGENTSERVICE._serialized_start=85
  _AGENTSERVICE._serialized_end=151
# @@protoc_insertion_point(module_scope)
