# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from runtime_api import frame_transport_pb2 as runtime__api_dot_frame__transport__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\x1a!runtime_api/frame_transport.proto\"Z\n\x0cInferRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12&\n\x05\x66rame\x18\x02 \x01(\x0b\x32\x17.runtime.FrameReference\x12\x14\n\x0cretain_frame\x18\x03 \x01(\x08\"\x1f\n\rInferResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2B\n\x0c\x41gentService\x12\x32\n\x05Infer\x12\x13.agent.InferRequest\x1a\x14.agent.InferResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERREQUEST']._serialized_start=57
  _globals['_INFERREQUEST']._serialized_end=147
  _globals['_INFERRESPONSE']._serialized_start=149
  _globals['_INFERRESPONSE']._serialized_end=180
  _globals['_AGENTSERVICE']._serialized_start=182
  _globals['_AGENTSERVICE']._serialized_end=248
# @@protoc_insertion_point(module_scope)
