config:
  merge:
    max_payload: 8388608

  leafnodes:
    enabled: true
    merge:
      remotes:
        - urls:
            - nats://leaf:change-me-leaf-password@CHANGE_ME_CLOUD_HOST:7422

  monitor:
    enabled: true

  jetstream:
    enabled: true
    fileStore:
      enabled: false
      pvc:
        enabled: false
    memoryStore:
      enabled: true
      maxSize: 1Gi

service:
  merge:
    spec:
      type: ClusterIP

container:
  image:
    registry: docker.m.daocloud.io

reloader:
  image:
    registry: docker.m.daocloud.io

natsBox:
  enabled: true
  container:
    image:
      registry: docker.m.daocloud.io

promExporter:
  enabled: false
