apiVersion: apps/v1
kind: Deployment
metadata:
  name: cooperativefeaturefusiondetectionviz-agent
  labels:
    app: cooperativefeaturefusiondetectionviz-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cooperativefeaturefusiondetectionviz-agent
  template:
    metadata:
      labels:
        app: cooperativefeaturefusiondetectionviz-agent
    spec:
      containers:
        - name: cooperativefeaturefusiondetectionviz-agent
          image: cooperativefeaturefusiondetectionviz-agent:0.1.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9032
              name: http
          env:
            - name: A2A_AGENT_URL
              value: http://192.168.49.2:30392
            - name: MODEL_CHECKPOINT_PATH
              value: /app/checkpoints/point_pillar_where2comm/
            - name: QT_GRAPHICSSYSTEM
              value: native
            - name: NATS_SERVERS
              value: nats://nats:4222
            - name: NATS_SERVER_URL
              value: nats://nats:4222
            - name: NATS_JETSTREAM_DOMAIN
              value: hub
            - name: NATS_STREAM_SUBJECTS
              value: workflow.>
            - name: NATS_SUBJECT
              value: workflow.demo.perception2feature.result.dx86.0601
            - name: NATS_DURABLE
              value: workflow-demo-perception2feature-result-dx86-0601
          resources:
            requests:
              nvidia.com/gpu: "1"
            limits:
              nvidia.com/gpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: cooperativefeaturefusiondetectionviz-agent
  labels:
    app: cooperativefeaturefusiondetectionviz-agent
spec:
  selector:
    app: cooperativefeaturefusiondetectionviz-agent
  ports:
    - name: http
      protocol: TCP
      nodePort: 30392
      port: 9032
      targetPort: 9032
  type: NodePort
